Redshift (#105)
* add redsift cluster

currect error:
Error: InvalidVPCNetworkStateFault: Cannot create a publicly accessible cluster because customer VPC vpc-076a7c128ec4a2cf9 has no internet gateway attached.
	status code: 400, request id: 9d953180-c7de-41ab-8e67-099b3b2a969d

  on 70-redshift.tf line 83, in resource "aws_redshift_cluster" "redshift_cluster":
  83: resource "aws_redshift_cluster" "redshift_cluster" {

Co-authored-by: b-dalton <ben.dalton@madetech.com>
Co-authored-by: maysakanoni <maysa@madetech.com>

* Create internet gateway and attach to VPC, make rds cluster not publicly accessible

To do: make it so that it only deploys the rds cluster in staging

Co-authored-by: elena-vi <elena@madetech.com>
Co-authored-by: maysakanoni <maysa@madetech.com>

* move redshift into module and only deploy in staging and prod

Co-authored-by: b-dalton <ben.dalton@madetech.com>
Co-authored-by: maysakanoni <maysa@madetech.com>

* remove unnecessary internet gateway

Co-authored-by: elena <elena@madetech.com>

* Remove  unnessecary action from redshift policy

Co-authored-by: elena <elena@madetech.com>

* Add final snapshot identifier to redshift cluster

Co-authored-by: elena <elena@madetech.com>

* fix typo

Co-authored-by: b-dalton <ben.dalton@madetech.com>
Co-authored-by: maysakanoni <maysa@madetech.com>