add get glue job runs (#2274)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetJobRuns operation: User: arn:aws:sts::120038763019:assumed-role/mwaa_execution_role/AmazonMWAA-airflow is not authorized to perform: glue:GetJobRuns on resource: arn:aws:glue:eu-west-2:120038763019:job/Copy parking Liberator landing zone to raw because no identity-based policy allows the glue:GetJobRuns action