Update parking_permit_denormalised_gds_street_llpg.py (#825)
Keep getting error message job failed.  Created terraform script in pre-production and ran with success.  This needs to be applied to Production. 

Error message from AWS: 
"The Glue job, parking_permit_denormalised_gds_street_llpg, failed with error:

AnalysisException: "cannot resolve '`ltn_london_fields.uprn`' given input columns: [parking_permit_denormalised_data.payment_by, street.SR_PARENT_UPRN, parking_permit_denormalised_data.make, parking_permit_denormalised_data.cpz_name, street.SR_LAST_UPDATED_TX_STAMP, street.SR_SAO_TEXT, llpg.longitude, street.SR_LATITUDE, llpg.blpu_class, llpg.unit_number, llpg.line3, street.SR_POST_CODE, street.SR_CREATED_TX_STAMP, street.SR_CPZ_NAME, llpg.import_date, llpg.postcode_nospace, llpg.building_number, street.SR_Y, parking_permit_denormalised_data.end_date, parking_permit_denormalised_data.quantity, parking_permit_denormalised_data.application_date, street.SR_STREET_END_Y, parking_permit_denormalised_data.approval_type, parking_permit_denormalised_data.primary_phone, street.SR_ADDRESS2, parking_permit_denormalised_data.Rn, parking_permit_denormalised_data.permit_reference, parking_permit_denormalised_data.start_date, street.USRN, street.SR_STREET_START_X, street.SR_ward_name, street.SR_IN_CONGESTION_CHARGE_ZONE, pa

Job Run ID: jr_653179f24c6264b3cd519d84b511fdec8478dc3908ee6ebada2ca7861e2e2ae5
Time of failure: Fri Jul 22 2022 04:34:53 GMT+0000 (Coordinated Universal Time)
Job start time: Fri Jul 22 2022 04:29:57 GMT+0000 (Coordinated Universal Time)
Job end time: Fri Jul 22 2022 04:33:53 GMT+0000 (Coordinated Universal Time)
Glue job last modified on: Wed Jul 20 2022 13:53:09 GMT+0000 (Coordinated Universal Time)

To investigate this error:
1. log into the AWS Prod environment via the Hackney SSO https://hackney.awsapps.com/start#/
2. view the Glue job run details here https://eu-west-2.console.aws.amazon.com/gluestudio/home?region=eu-west-2#/job/parking_permit_denormalised_gds_street_llpg/run/jr_653179f24c6264b3cd519d84b511fdec8478dc3908ee6ebada2ca7861e2e2ae5

--
If you wish to stop receiving notifications from this topic, please click or visit the link below to unsubscribe:
https://sns.eu-west-2.amazonaws.com/unsubscribe.html?SubscriptionArn=arn:aws:sns:eu-west-2:365719730767:glue-failure-notification-parking:e3883c91-dc36-486f-b58a-2c6ad28ad17b&Endpoint=saml-aws-data-platform-collaborator-parking@hackney.gov.uk

Please do not reply directly to this email. If you have any questions or comments regarding this email, please contact us at https://aws.amazon.com/support"