Fix Queue visibility timeout.
See this article for more information about why the SQS Queues
"visibility_timeout_seconds" needs to match the Lambda functions
timeout.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html

Error: error creating Lambda Event Source Mapping (arn:...): InvalidParameterValueException: Queue visibility timeout: 30 seconds is less than Function timeout: 900 seconds
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "b0a23d7a-b4fe-445d-b9cf-c070dde61e5b"
  },
  Message_: "Queue visibility timeout: 30 seconds is less than Function timeout: 900 seconds",
  Type: "User"
}